/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionOverview: typeof import('./src/components/sections/overview/SectionOverview.vue')['default']
  }
}

// For TSX support
declare global {
  const AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
  const AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SectionOverview: typeof import('./src/components/sections/overview/SectionOverview.vue')['default']
}